import { useMemo } from "react";
import JsBarcode from "jsbarcode";
import type { Deposit } from "@shared/types";
import { cn } from "@/lib/utils";
import { formatDepositValue, getDepositState, getExpiryLabel } from "./depositStatus";

interface DepositTicketProps {
  deposit: Deposit;
}

// Renders the barcode into a detached <svg> and returns its markup,
// or null when the code can't be encoded
const renderBarcodeSvg = (code: string, isGs1: boolean) => {
  const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
  try {
    JsBarcode(svg, code, {
      format: "CODE128",
      // GS1-128: adds the leading FNC1 the original voucher had - without it a till
      // may read the same digits but not recognise it as a GS1 voucher
      ean128: isGs1,
      background: "transparent",
      lineColor: "#0c0a09",
      height: 72,
      margin: 0,
      displayValue: false,
    });
  } catch {
    return null;
  }
  // w-full + h-auto: stretches to the ticket width, keeps proportions
  svg.setAttribute("class", "h-auto w-full max-w-80");
  svg.setAttribute("preserveAspectRatio", "none");
  return svg.outerHTML;
};

// Half-circle "punched" notch on the tear line. The ticket clips it to a half,
// and the background colour makes it look cut out of the paper.
function Notch({ side }: { side: "left" | "right" }) {
  return (
    <span
      aria-hidden
      className={cn(
        "absolute top-1/2 size-5 -translate-y-1/2 rounded-full bg-background shadow-[inset_0_0_0_1px_rgb(0_0_0/0.08)]",
        side === "left" ? "-left-2.5" : "-right-2.5",
      )}
    />
  );
}

// The voucher as a paper ticket: always white (the cashier's scanner needs dark-on-light),
// with an outline + shadow in light mode so it doesn't melt into a white background.
// Code128 - the same format the backend reads from the photo.
export function DepositTicket({ deposit }: DepositTicketProps) {
  const svgMarkup = useMemo(
    () => (deposit.code ? renderBarcodeSvg(deposit.code, deposit.code_format === "gs1") : null),
    [deposit.code, deposit.code_format],
  );
  const state = getDepositState(deposit);
  const stamp =
    state === "used"
      ? { label: "Wykorzystany", className: "border-red-600/70 text-red-600/70" }
      : state === "expired"
        ? { label: "Po terminie", className: "border-neutral-500/70 text-neutral-500/80" }
        : null;

  return (
    <div
      className={cn(
        "relative overflow-hidden rounded-2xl bg-white text-neutral-900",
        "shadow-[0_8px_24px_-8px_rgb(0_0_0/0.25)] ring-1 ring-black/10 dark:shadow-none dark:ring-0",
      )}
    >
      {/* TOP: shop + value */}
      <div className="flex items-start justify-between gap-3 px-5 pt-4 pb-4">
        <div className="min-w-0">
          <p className="text-[11px] tracking-wider text-neutral-500 uppercase">Kupon kaucyjny</p>
          <p className="truncate text-lg font-semibold">{deposit.shop_name ?? "Bez sklepu"}</p>
          <p className="text-xs text-neutral-500">{getExpiryLabel(deposit)}</p>
        </div>
        <p className="shrink-0 font-mono text-2xl font-semibold text-orange-600">
          {formatDepositValue(deposit.value)}
        </p>
      </div>

      {/* TEAR LINE */}
      <div className="relative h-0">
        <Notch side="left" />
        <div className="mx-4 border-t-2 border-dashed border-neutral-200" />
        <Notch side="right" />
      </div>

      {/* BOTTOM: barcode */}
      <div className="flex flex-col items-center gap-2 px-5 pt-4 pb-4">
        {svgMarkup ? (
          // Markup is generated by JsBarcode (only rects), not user HTML
          <div
            className={cn("flex w-full justify-center", stamp && "opacity-30")}
            dangerouslySetInnerHTML={{ __html: svgMarkup }}
          />
        ) : (
          <p className="py-6 text-sm text-neutral-500">
            {deposit.code ? "Nie udało się wygenerować kodu" : "Ten kupon nie ma zapisanego kodu"}
          </p>
        )}
        {deposit.code && (
          <span className="font-mono text-sm tracking-[0.3em] text-neutral-700">{deposit.code}</span>
        )}
      </div>

      {/* Stamp across the ticket: red for used, grey for past the date */}
      {stamp && (
        <div className="pointer-events-none absolute inset-0 flex items-center justify-center">
          <span
            className={cn(
              "-rotate-12 rounded-lg border-[3px] px-3 py-1 text-xl font-bold tracking-widest uppercase",
              stamp.className,
            )}
          >
            {stamp.label}
          </span>
        </div>
      )}
    </div>
  );
}
